services:
  nginx:
    container_name: yii_nginx
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./www:/var/www
      - ./vhost.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    container_name: yii_php
    build: ./images/php81fpm
    volumes:
      - ./www:/var/www
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql
    ports:
    - 3306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      - MYSQL_USER=yii
      - MYSQL_PASSWORD=yii
      - MYSQL_ROOT_PASSWORD=yii
      - MYSQL_DATABASE=yii

  phpmyadmin:
    container_name: yii_phpmyadmin
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      PMA_USER: yii
      PMA_PASSWORD: yii
    depends_on:
      - php
      - mysql